import { Inter } from "next/font/google";
import "./globals.css";
import Header from "./_components/Header";
import Footer from "./_components/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
    title: "Learn Next js",
    description: "Generated by create next app",
};

export default function RootLayout({ children })
{
    return (
        <html lang="en">
            <body className={inter.className} >
                <div className="h-screen flex flex-col justify-between">
                <Header />
                <div className="flex justify-center my-auto">
                    {children}
                </div>
                <Footer />
                </div>
            </body>
        </html>
    );
}